# Generated by Django 2.2.6 on 2019-10-19 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_orderpickup'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='phone_number',
            new_name='phone',
        ),
    ]
