# Generated by Django 2.2.6 on 2019-10-19 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20191019_2318'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='order_id',
            new_name='order',
        ),
    ]
