# Generated by Django 2.2.6 on 2019-10-19 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20191020_0003'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='privkey',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='user',
            name='pubkey',
            field=models.TextField(default=''),
        ),
    ]
