# Generated by Django 2.2.6 on 2019-10-19 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20191020_0152'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='is_done',
            field=models.BooleanField(default=False),
        ),
    ]
